**/fly.toml
**/.git/

**/*.sqlite3
!db/hlDjangoDb.sqlite3

**/*_secret.py
!code/hldjango/settingsdir/standalone_docker_secret.py

**/*.ps1
**/*.bat
**/*.log
**/log*.txt
**/UNUSED
**/OLDJUNK
**/OldJunk
**/*.bak

**/__pycache__
*.pyc

media/games/*