# Generated by Django 5.1.6 on 2025-08-20 20:07

from django.db import migrations, models

# python modules
import pathlib
import datetime
import os


# backfill missing fields for game files
def backfill_file_metadata(apps, schema_editor):
    MyModel = apps.get_model("games", "gamefile")

    for obj in MyModel.objects.all():
        if obj.filefield and not obj.fileName:
            path = obj.filefield.name
            obj.fileName = pathlib.Path(path).name

            try:
                stat = os.stat(path)
                #stat = obj.filefield.storage.stat(path)
                obj.fileSize = stat.st_size
                obj.fileDate = datetime.datetime.fromtimestamp(stat.st_mtime)
            except (OSError, FileNotFoundError):
                obj.fileSize = None
                obj.fileDate = None

            obj.save()



class Migration(migrations.Migration):

    dependencies = [
        ("games", "0047_game_adminsortkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamefile",
            name="fileDate",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="gamefile",
            name="fileName",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name="gamefile",
            name="fileSize",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),

        # backfill data
        migrations.RunPython(backfill_file_metadata),
    ]
