# Generated by Django 5.1.6 on 2025-08-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0048_gamefile_filedate_gamefile_filename_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamefile",
            name="fileDate",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gamefile",
            name="fileName",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="gamefile",
            name="fileSize",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
