# Generated by Django 5.1.6 on 2025-08-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0049_alter_gamefile_filedate_alter_gamefile_filename_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamefile",
            name="fileDate",
        ),
        migrations.RemoveField(
            model_name="gamefile",
            name="fileName",
        ),
        migrations.RemoveField(
            model_name="gamefile",
            name="fileSize",
        ),
    ]
