# Generated by Django 5.1.6 on 2025-08-20 20:29

from django.db import migrations, models
from django.conf import settings
from django.utils import timezone

# python modules
import pathlib
import datetime
import os


# backfill missing fields for game files
def backfill_file_metadata(apps, schema_editor):
    MyModel = apps.get_model("games", "gamefile")

    for obj in MyModel.objects.all():
        if obj.filefield and not obj.fileName:
            path = obj.filefield.name
            full_path = os.path.join(settings.MEDIA_ROOT, path)
            obj.fileName = pathlib.Path(path).name

            try:
                stat = os.stat(full_path)
                obj.fileSize = stat.st_size
                naive_dt = datetime.datetime.fromtimestamp(stat.st_mtime)
                obj.fileDate = timezone.make_aware(naive_dt, timezone.get_current_timezone())
            except (OSError, FileNotFoundError):
                obj.fileSize = None
                obj.fileDate = None
                print("ERROR: FAILED TO BACKFILL GAME FILE NAME/DATE/SIZE; FILE NOT FOUND (might be just a deleted file needing reconciling): '{}' mapped to '{}'".format(path, full_path))

            obj.save()



class Migration(migrations.Migration):

    dependencies = [
        ("games", "0050_remove_gamefile_filedate_remove_gamefile_filename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamefile",
            name="fileDate",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gamefile",
            name="fileName",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="gamefile",
            name="fileSize",
            field=models.BigIntegerField(blank=True, null=True),
        ),

        # backfill data
        migrations.RunPython(backfill_file_metadata),
    ]
