# Generated by Django 5.1.6 on 2025-08-20 20:45

from django.db import migrations, models


from games.utils.gameMigrationHelpers import backfill_gamefile_metadata_fileNameSizeDate  # must remain stable forever

class Migration(migrations.Migration):

    dependencies = [
        ("games", "0052_remove_gamefile_filedate_remove_gamefile_filename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamefile",
            name="fileDate",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gamefile",
            name="fileName",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="gamefile",
            name="fileSize",
            field=models.BigIntegerField(blank=True, null=True),
        ),

        # backfill data
        migrations.RunPython(backfill_gamefile_metadata_fileNameSizeDate),
    ]
